
# GET http://localhost:3000/user



POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "namth",
  "password": "123456",
  "name": "nam tran 1",
  "role": "USER"
}